<?php

namespace App\Services\Shipping;

use App\Models\Shipment;
use App\Models\ShippingLabel;
use App\Services\Shipping\Barcode\Code128;
use Illuminate\Support\Facades\View;

/**
 * Renders a packing slip (spec 04 §4.9) — generated by us, never the carrier. Bilingual, one per
 * shipment, with a Code128 barcode of the reference. Stored as an html shipping_labels artefact so
 * merchants print from the browser (no PDF toolchain dependency). Deliberately carries NO prices —
 * many merchants ship gifts — and no internal cost data.
 */
class PackingSlipRenderer
{
    public function __construct(private readonly LabelStorageService $labels)
    {
    }

    public function render(Shipment $shipment): ShippingLabel
    {
        $shipment->loadMissing(['order.items', 'items', 'packages', 'shipToAddress', 'store']);

        $settings = $shipment->store?->shipping_settings ?? [];
        $items = $shipment->items->isNotEmpty()
            ? $shipment->items->map(fn ($i) => ['sku' => $i->sku, 'name' => $i->name, 'quantity' => (int) $i->quantity])
            : $shipment->order?->items->map(fn ($i) => ['sku' => $i->sku, 'name' => $i->name, 'quantity' => (int) $i->quantity]) ?? collect();

        $html = View::make('shipping.packing-slip', [
            'shipment' => $shipment,
            'merchantName' => $settings['brand_name'] ?? $shipment->store?->name ?? 'Hubby',
            'logoUrl' => $settings['logo_url'] ?? null,
            'footer' => $settings['packing_slip_footer'] ?? null,
            'orderNumber' => $shipment->order?->external_id,
            'to' => $shipment->shipToAddress,
            'items' => $items,
            'packageCount' => max(1, (int) $shipment->package_count),
            'barcodeSvg' => (new Code128())->svg($shipment->reference),
            'isCod' => (bool) $shipment->is_cod,
        ])->render();

        return $this->labels->store($shipment, [
            'format' => 'html',
            'content_base64' => base64_encode($html),
        ], 'packing_slip');
    }

    /** The stored packing slip for a shipment, rendering one if none exists yet. */
    public function forShipment(Shipment $shipment): ShippingLabel
    {
        $existing = ShippingLabel::where('shipment_id', $shipment->id)
            ->where('type', 'packing_slip')
            ->whereNull('voided_at')
            ->latest('id')
            ->first();

        return $existing ?? $this->render($shipment);
    }
}
